# Building Predictive Models

In [10]:
import pandas as pd 
import numpy as np
import os


### Import Data

In [11]:
# Set the path of the processed data

processed_data_path = os.path.join(os.path.pardir, 'data', 'processed')
train_file_path = os.path.join(processed_data_path, 'train.csv')
test_file_path = os.path.join(processed_data_path, 'test.csv')

In [12]:
train_df = pd.read_csv(train_file_path, index_col='PassengerId')
test_df = pd.read_csv(test_file_path, index_col='PassengerId')

In [13]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Survived            891 non-null    int64  
 1   Age                 891 non-null    float64
 2   Fare                891 non-null    float64
 3   FamilySize          891 non-null    int64  
 4   IsMother            891 non-null    int64  
 5   IsMale              891 non-null    int64  
 6   Deck_A              891 non-null    int64  
 7   Deck_B              891 non-null    int64  
 8   Deck_C              891 non-null    int64  
 9   Deck_D              891 non-null    int64  
 10  Deck_E              891 non-null    int64  
 11  Deck_F              891 non-null    int64  
 12  Deck_G              891 non-null    int64  
 13  Deck_Z              891 non-null    int64  
 14  Pclass_1            891 non-null    int64  
 15  Pclass_2            891 non-null    int64  
 16  Pclass_3

In [14]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 418 non-null    float64
 1   Fare                418 non-null    float64
 2   FamilySize          418 non-null    int64  
 3   IsMother            418 non-null    int64  
 4   IsMale              418 non-null    int64  
 5   Deck_A              418 non-null    int64  
 6   Deck_B              418 non-null    int64  
 7   Deck_C              418 non-null    int64  
 8   Deck_D              418 non-null    int64  
 9   Deck_E              418 non-null    int64  
 10  Deck_F              418 non-null    int64  
 11  Deck_G              418 non-null    int64  
 12  Deck_Z              418 non-null    int64  
 13  Pclass_1            418 non-null    int64  
 14  Pclass_2            418 non-null    int64  
 15  Pclass_3            418 non-null    int64  
 16  Title

In [15]:
x = train_df.loc[:,'Age':].values.astype('float')
y= train_df['Survived'].ravel()

In [16]:
print(x.shape, y.shape)
print(x.ndim)

(891, 32) (891,)
2


In [17]:
# train test split

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)
print(x_test.shape, y_train.shape)

(179, 32) (712,)


In [18]:
print('Mean survival in train: {0:.3f}'.format(np.mean(y_train)))
print('Mean survival in test: {0:.3f}'.format(np.mean(y_test)))

Mean survival in train: 0.383
Mean survival in test: 0.385


In [19]:
import sklearn

In [20]:
sklearn.__version__

'0.24.2'

In [21]:
from sklearn.dummy import DummyClassifier

In [22]:
model_dummy = DummyClassifier(strategy='most_frequent',random_state=0)

In [23]:
model_dummy.fit(x_train, y_train)

DummyClassifier(random_state=0, strategy='most_frequent')

In [24]:
print('Score for baseline model: {0:.2f}'.format(model_dummy.score(x_test,y_test)))

Score for baseline model: 0.61


In [25]:
# Performance Metrics 

from sklearn.metrics import accuracy_score,confusion_matrix, precision_score, recall_score

In [26]:
# Accuracy
print('Accuracy for baseline model: {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(x_test))))

Accuracy for baseline model: 0.61


In [27]:
# Confusion matrix 

print('Confusion matrix for baseline model: \n {0}'.format(confusion_matrix(y_test, model_dummy.predict(x_test))))

Confusion matrix for baseline model: 
 [[110   0]
 [ 69   0]]


In [28]:
print('Precision for baseline model: {0:.2f}'.format(precision_score(y_test, model_dummy.predict(x_test))))
print('Recall Score for baseline model: {0:.2f}'.format(recall_score(y_test, model_dummy.predict(x_test),zero_division=0)))

Precision for baseline model: 0.00
Recall Score for baseline model: 0.00


/Users/kiran/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### First Kaggle Submission

In [29]:
test_x = test_df.values.astype('float')

In [30]:
predictions = model_dummy.predict(test_x)

In [31]:
df_submissions = pd.DataFrame({'PassengerId': test_df.index, 'Survived': predictions})

In [32]:
df_submissions.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [33]:
submission_data_path = os.path.join(os.path.pardir,'data','external')
submission_file_path = os.path.join(submission_data_path, '01_dummy.csv')

In [34]:
df_submissions.to_csv(submission_file_path, index=False)

In [35]:
def get_submission_file(model, filename):
    
    # converting to the matrix 
    test_x = test_df.values.astype('float')
    
    # Make Predictions
    predictions = model.predict(test_x)
    
    #Submission of dataframe
    df_submission = pd.DataFrame({'PassangerId': test_df.index, 'Survived': predictions})
    
    submission_data_path = os.path.join(os.path.pardir,'data','external')
    submission_file_path = os.path.join(submission_data_path, filename)
    
    #Write to the CSV File
    df_submissions.to_csv(submission_file_path, index=False)

In [45]:
# get Submission file 
get_submission_file(model_dummy, '01_dummy.csv')

## Logistic Regression Model

In [37]:
from sklearn.linear_model import LogisticRegression

In [47]:
# Create model
model_lr_1 = LogisticRegression(random_state=0)

In [48]:
# trainmodel 
model_lr_1.fit(x_train, y_train)

/Users/kiran/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [49]:
print(model_lr_1.score(x_test, y_test))

0.8324022346368715


In [41]:
print('Confusion matrix for baseline model: \n {0}'.format(confusion_matrix(y_test, model_lr_1.predict(x_test))))
print('Precision for baseline model: {0:.2f}'.format(precision_score(y_test, model_lr_1.predict(x_test))))
print('Recall Score for baseline model: {0:.2f}'.format(recall_score(y_test, model_lr_1.predict(x_test),zero_division=0)))

Confusion matrix for baseline model: 
 [[95 15]
 [15 54]]
Precision for baseline model: 0.78
Recall Score for baseline model: 0.78


In [42]:
model_lr_1.coef_

array([[-0.03260424,  0.00423411, -0.52583955,  0.63338863, -1.11333172,
        -0.01555795, -0.30895353, -0.52372882,  0.40326565,  0.97734353,
         0.27831598, -0.28577863, -0.51550441,  0.58900067,  0.13374493,
        -0.71334377,  0.24025509,  1.09212563,  0.1521471 , -1.55749122,
         0.73033136, -0.15453006, -0.49343607, -0.12065825, -0.03884562,
         0.00635398,  0.16255171,  0.12306187,  0.11818288, -0.23184292,
        -0.17826498,  0.1876668 ]])

In [44]:
get_submission_file(model_lr_1,'02_lr.csv')