In [1]:
import pandas as pd

In [4]:
insurance = pd.read_csv("https://raw.githubusercontent.com/vishurudratrainer/notebooks/main/insurance.csv")

In [5]:
insurance.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [6]:
insurance.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [31]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
columns = ['sex', 'smoker', 'region']
for column in columns:
    insurance[column] = le.fit_transform(insurance[column])
    

### Inverse Transformation

In [37]:
for label in labels:
    print(label)
    print(labels[label].inverse_transform(insurance[label]))


sex
[0 1 1 ... 0 0 0]
smoker
[1 0 0 ... 0 0 1]
region
[3 2 2 ... 2 3 1]


In [19]:
insurance.corr()

age       sex       bmi  children    smoker    region   charges
age       1.000000 -0.020856  0.109272  0.042469 -0.025019  0.002127  0.299008
sex      -0.020856  1.000000  0.046371  0.017163  0.076185  0.004588  0.057292
bmi       0.109272  0.046371  1.000000  0.012759  0.003750  0.157566  0.198341
children  0.042469  0.017163  0.012759  1.000000  0.007673  0.016569  0.067998
smoker   -0.025019  0.076185  0.003750  0.007673  1.000000 -0.002181  0.787251
region    0.002127  0.004588  0.157566  0.016569 -0.002181  1.000000 -0.006208
charges   0.299008  0.057292  0.198341  0.067998  0.787251 -0.006208  1.000000

In [20]:
x=insurance.drop('charges', axis=1)
y=insurance['charges']

In [21]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)

In [22]:
from sklearn.linear_model import LinearRegression
le = LinearRegression()
le.fit(x_train,y_train)


LinearRegression()

In [23]:
y_predict = le.predict(x_test)

In [24]:
result = pd.DataFrame({"actual": y_test, "predicted": y_predict})
result.head(5)

actual     predicted
578    9724.53000  11051.549098
610    8547.69130   9821.281107
569   45702.02235  37867.572209
1034  12950.07120  16125.705792
198    9644.25250   6920.271325

In [25]:
from sklearn.metrics import mean_squared_error, r2_score
print(mean_squared_error(y_test, y_predict))

print(r2_score(y_test, y_predict))

33311355.281859957
0.7911113876316934


In [27]:
import numpy as np
np.var(result)

actual       1.594695e+08
predicted    1.152227e+08
dtype: float64