In [14]:
import numpy as np
import pandas as pd



In [23]:
ages=np.array([range(1,11)])
ages.shape
ages.ndim

2

In [25]:
a1 = np.array([7,9,65,33,85,90])
print(a1)

a2 = np.array([[1,2,4],[2,3,0],[0,5,1]])
print(a2)

[ 7  9 65 33 85 90]
[[1 2 4]
 [2 3 0]
 [0 5 1]]


In [31]:
a2.reshape(1,1,1,3,3)


array([[[[[1, 2, 4],
          [2, 3, 0],
          [0, 5, 1]]]]])

In [37]:
c1 = np.random.randint(0,110,50)
print(c1)
c2=np.random.rand(50)
print(c2)

[102  21  40  86  16  49  20  40  13  51  25  52   6  83  82 101  94 104
  93  88  36  95  13  89   3  96  17 104 108  43  79  79  48  56  14  28
  40  25  80   1 108  41  42 100 106  17  86   1  85  72]
[0.70752361 0.60894606 0.0720865  0.70726253 0.46213563 0.81411813
 0.87050153 0.08060445 0.41621335 0.34629451 0.17812212 0.38825538
 0.78110193 0.84386065 0.64954262 0.69935822 0.2753047  0.39052629
 0.90873667 0.6455118  0.38375542 0.92177056 0.13315349 0.20823125
 0.58499109 0.18288646 0.17511016 0.91086696 0.83123404 0.65994226
 0.77831323 0.99223064 0.82558203 0.14911213 0.85547714 0.31105379
 0.00436416 0.67737993 0.78594547 0.57595054 0.94273547 0.64912402
 0.75457248 0.22520995 0.35742398 0.91846713 0.96148957 0.36873233
 0.67940036 0.88876725]


In [41]:
c3=np.random.choice(['french', 'english'],50)
print(c3)

data = np.column_stack((c1,c2,c3)).flatten()
print(data)

['french' 'english' 'english' 'english' 'english' 'french' 'english'
 'french' 'french' 'french' 'english' 'french' 'french' 'english'
 'english' 'english' 'english' 'french' 'english' 'english' 'english'
 'french' 'english' 'english' 'english' 'english' 'english' 'english'
 'french' 'english' 'english' 'english' 'english' 'french' 'french'
 'french' 'english' 'french' 'french' 'english' 'french' 'french'
 'english' 'english' 'english' 'french' 'french' 'english' 'french'
 'french']
['102' '0.707523605076646' 'french' '21' '0.6089460639346865' 'english'
 '40' '0.0720864950788197' 'english' '86' '0.7072625297003102' 'english'
 '16' '0.46213562502491423' 'english' '49' '0.8141181296903726' 'french'
 '20' '0.8705015304100957' 'english' '40' '0.08060445387361892' 'french'
 '13' '0.41621334996797454' 'french' '51' '0.3462945146805667' 'french'
 '25' '0.17812211883275075' 'english' '52' '0.3882553825558023' 'french'
 '6' '0.7811019256330137' 'french' '83' '0.8438606456942165' 'english'
 '82'

In [46]:
np.random.choice(['french', 'english'],50,p=(0.5,0.5))

array(['french', 'french', 'english', 'english', 'english', 'english',
       'english', 'french', 'french', 'english', 'french', 'french',
       'english', 'french', 'french', 'french', 'english', 'english',
       'english', 'french', 'english', 'english', 'english', 'english',
       'english', 'french', 'french', 'english', 'english', 'french',
       'english', 'french', 'french', 'english', 'french', 'english',
       'french', 'english', 'english', 'english', 'english', 'english',
       'french', 'english', 'french', 'french', 'french', 'french',
       'english', 'french'], dtype='<U7')

In [52]:
np.linspace(0,50,11)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [54]:
np.repeat(2,10)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [61]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [63]:
five_time_table =np.arange(0,55,5)

In [65]:
print(five_time_table * 2)
print(five_time_table + 10)
print(five_time_table < 25)

[  0  10  20  30  40  50  60  70  80  90 100]
[10 15 20 25 30 35 40 45 50 55 60]
[ True  True  True  True  True False False False False False False]
